
version : "3"
services:
  geth:
    container_name : ethereum-node
    image: ethereum/client-go
    ports:
      - "8545:8545"
      - "30303:30303"
    volumes: 
      - ./share:/root
    working_dir : /root
    entrypoint : sh